# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_candidates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinion',
            old_name='question',
            new_name='mentor',
        ),
    ]
